/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/machines` | `/machines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `/orders/add`; params?: Router.UnknownInputParams; } | { pathname: `/machines/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/catalog/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/machines` | `/machines`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownOutputParams; } | { pathname: `/orders/add`; params?: Router.UnknownOutputParams; } | { pathname: `/machines/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/orders/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/catalog/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/machines${`?${string}` | `#${string}` | ''}` | `/machines${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/orders${`?${string}` | `#${string}` | ''}` | `/orders${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/catalog${`?${string}` | `#${string}` | ''}` | `/catalog${`?${string}` | `#${string}` | ''}` | `/orders/add${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/machines` | `/machines`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/orders` | `/orders`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/catalog` | `/catalog`; params?: Router.UnknownInputParams; } | { pathname: `/orders/add`; params?: Router.UnknownInputParams; } | `/machines/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/orders/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/catalog/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/machines/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/orders/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/catalog/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
